CREATE TABLE user (
  user_id INTEGER AUTO_INCREMENT PRIMARY KEY,
  first_name VARCHAR(30) NOT NULL,
  last_name VARCHAR(30) NOT NULL,
  location VARCHAR(30) NOT NULL,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT barter_user UNIQUE (user_id)
);

CREATE TABLE items_available (
item_id INTEGER AUTO_INCREMENT PRIMARY KEY,
item VARCHAR(30) NOT NULL,
description TEXT,
created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
CONSTRAINT barter_item UNIQUE (item_id)
);